// Questions should be broken up into categories for scoring
// Each group may score differently

const Questions = [
	'I am always prepared.',
	'I have a kind word for everyone.',
	'I feel comfortable around people.',
	'I often feel blue.',
	'I believe in the importance of art.',
	'I feel I am better than other people.',
	'I avoid taking on a lot of responsibility.',
	'I make friends easily.',
	'There are many things that I do not like about myself.',
	'I am interested in the meaning of things.',
	'I treat everyone with kindness and sympathy.',
	'I get chores done right away.',
	'I am skilled in handling social situations.',
	'I am often troubled by negative thoughts.',
	'I enjoy going to art museums.',
	'I accept people the way they are.',
	'It’s important to me that people are on time.',
	'I am the life of the party.',
	'My moods change easily.',
	'I have a vivid imagination.',
	'I take care of other people before taking care of myself.',
	'I make plans and stick to them.',
	"I don't like to draw attention to myself.",
	'I often feel anxious about what could go wrong.',
	'I enjoy hearing new ideas.',
	'I start arguments just for the fun of it.',
	'I always make good use of my time.',
	'I have a lot to say.',
	'I often worry that I am not good enough.',
	'I am not interested in abstract ideas.',
	'I criticize other people.',
	'I find it difficult to get to work.',
	'I stay in the background.',
	'I seldom feel blue.',
	'I do not like art.',
	'I stop what I am doing to help other people.',
	'I change my plans frequently.',
	"I don't talk a lot.",
	'I feel comfortable with myself.',
	'I avoid philosophical discussions.',
	'Original',
	'Systematic',
	'Shy',
	'Soft-Hearted',
	'Tense',
	'Inquisitive',
	'Forgetful',
	'Reserved',
	'Agreeable',
	'Nervous',
	'Creative',
	'Self-Disciplined',
	'Outgoing',
	'Charitable',
	'Moody',
	'Imaginative',
	'Organized',
	'Talkative',
	'Humble',
	'Pessimistic'
];

export default Questions;
